### ISSUE TITLE
How can I get Mrrg?

### ISSUE THREAD

**Issue by 1bing2** [tancheng/CGRA-Mapper#14]
Hi ,cheng
Where can I generate or obtain the MRRG of CGRA?
Thank you!
Have a nice Day!

**Comment by tancheng** [comment]
> Hi ,cheng Where can I generate or obtain the MRRG of CGRA? Thank you! Have a nice Day!

Hi, there is no visualization of MRRG but it is create [here](https://github.com/tancheng/CGRA-Mapper/blob/9cd5280ebac4dbc9946369d2e8e590e8eaa73a7d/src/CGRA.cpp#L310).
