### ISSUE TITLE
Bugs about enabling load/store on specific tiles in CGRA.cpp

### ISSUE THREAD

**Issue by HobbitQia** [tancheng/CGRA-Mapper#22]
In CGRA.cpp:104-141, the code enables the load/store on specific CGRA nodes based on param.json and in the code below we count nodes that we enable to perform load or store operations.
``` C++
            // CGRA.cpp:120
            if ((iter->first).compare("store")) {
              storeCount += 1;
            }
            if ((iter->first).compare("load")) {
              loadCount += 1;
            }
```
However, since `compare` method will return 0 if they compare equal, when the condition is true (i.e. The return value does not equal 0) in the if clause, the string in the item of `t_additionalFunc` should be different from the string "store" or "load". In that case we should not increment the counter `storeCount` or `loadCount`. The correct code should be:
``` C++
            // CGRA.cpp:120
            if ((iter->first).compare("store")==0) {
              storeCount += 1;
            }
            if ((iter->first).compare("load")==0) {
              loadCount += 1;
            }
```

**Comment by HobbitQia** [comment]
The similar problems occur at CGRANode.cpp:409-424
``` C
bool CGRANode::enableFunctionality(string t_func) {
  if (t_func.compare("store")) {
    enableStore();
  } else if (t_func.compare("load")) {
    enableLoad();
  } else if (t_func.compare("return")) {
    enableReturn();
  } else if (t_func.compare("call")) {
    enableCall();
  } else if (t_func.compare("complex")) {
    enableComplex();
  } else {
    return false;
  }
  return true;
}
```
It should be:
``` C++
bool CGRANode::enableFunctionality(string t_func) {
  if (t_func.compare("store")==0) {
    enableStore();
  } else if (t_func.compare("load")==0) {
    enableLoad();
  } else if (t_func.compare("return")==0) {
    enableReturn();
  } else if (t_func.compare("call")==0) {
    enableCall();
  } else if (t_func.compare("complex")==0) {
    enableComplex();
  } else {
    return false;
  }
  return true;
}
```

**Comment by tancheng** [comment]
Thanks @HobbitQia, can you please make a PR for this simple change?
This set up/PR can also help us later sync on your local changes frequently.

**Comment by HobbitQia** [comment]
> Thanks @HobbitQia, can you please make a PR for this simple change? This set up/PR can also help us later sync on your local changes frequently.

Ok, I have created a [PR](https://github.com/tancheng/CGRA-Mapper/pull/23) here.
