### ISSUE TITLE
How to determine the latency of some DFG operations?

### ISSUE THREAD

**Issue by ShangkunLi** [tancheng/CGRA-Mapper#26]
Hi Cheng,

Just notice that in the [param.json](https://github.com/tancheng/CGRA-Mapper/blob/master/test/param.json#L19) file you let the latency of load/store operations to be 2. How did you get this value?

Thanks.

**Comment by tancheng** [comment]
I just try to make it parameterizable. It could be 1 or any value. But for now, our hardware only support single-cycle memory access.

**Comment by ShangkunLi** [comment]
Okay, thanks!
