### ISSUE TITLE
How to use isStaticElasticCGRA feature

### ISSUE THREAD

**Issue by sampsu** [tancheng/CGRA-Mapper#6]
Hello, 
Thanks for your public  CGRA mapper repository.
I am trying to use your git repo for elastic CGRA (isStaticElasticCGRA parameter=true).
Is static-elastic-CGRA feature still supported with the latest commit? I see that your HPCA version works for a simple kernel, but the same kernel does not get mapped successfully with the latest branch.

I have a few naive questions, if you would be kind enough to shed some light on.
1) Should the CGRA size be larger than (or equal to) the number-of-instructions in DFG for static-elastic-mapper?
2) What is necessary for the default mapper (isStaticElasticCGRA=false) to have "elastic" loads/stores?

Thank you,
Sam

**Comment by tancheng** [comment]
Hi @sampsu, I have enabled static mapping and it should work by renaming the [param_static.json](https://github.com/tancheng/CGRA-Mapper/blob/master/test/param_static.json) to `param.json`.
Based on your last comment, I don't think you need it anymore, but I still make it runnable :)
What you suggested is correct. There are different types of coarse-grained spatial accelerators with specific tradeoffs between compiler implementation and hardware cost/engineering effort.
But please keep in mind that the `elastic` feature proposed in `HPCA'21` requires manipulating the clock trees (yes, it requires multiple clock trees) to enable DVFS, which is a plus or orthogonal to dynamic/static CGRAs.

**Comment by sampsu** [comment]
Great. This is very helpful.
